// import type { NextApiRequest, NextApiResponse } from 'next';
import { NextApiRequest, NextApiResponse } from 'next';


const handler = (req: NextApiRequest, res: NextApiResponse) => {
  const plans = [
    {
      nome: 'Controle Start',
      idPlano: '1987',
      gb: 10,
      descricao: 'Ideal para uso básico de internet.',
      qtd: 5,
      bonus: '5GB ',
      imagem: '/img/planos/semplano.png',
      valor: '39,90',
      url: 'https://example.com/contratar/basico',
      minutos: 60,
      sms: 60,
      cobertura: '4G/5G',
      chipHello: 'GRÁTIS',
      frete: '9,90',
      total: '49,80',
    },
    {
      nome: 'Controle Essentials',
      idPlano: '1988',
      gb: 16,
      descricao: 'Ideal para ouvir suas músicas em dados móveis e engajar nas redes sociais sem se preocupar',
      qtd: 8,
      bonus: '8GB',
      imagem: '/img/planos/semplano.png',
      valor: '49,90',
      url: 'https://example.com/contratar/intermediario',
      minutos: 75,
      sms: 70,
      cobertura: '4G/5G',
      chipHello: 'GRÁTIS',
      frete: '9,90',
      total: '59,80',
    },
    {
      nome: 'Controle Cast + MAX',
      idPlano: '1989',
      gb: 25,
      descricao: 'Streaming e Compartilhamento? O plano Cast tem a corbertura de dados que os influencers precisam.',
      qtd: 12,
      bonus: '13GB',
      imagem: '/img/max-1@2x.png',
      valor: '89,90',
      url: 'https://example.com/contratar/intermediario',
      minutos: 90,
      sms: 90,
      cobertura: '4G/5G',
      chipHello: 'GRÁTIS',
      frete: 'GRÁTIS',
      total: '89,90',
    },
    {
      nome: 'Controle Plus + MAX',
      idPlano: '1990',
      gb: 40,
      descricao: 'Para os apaixonados por filmes, séries e vídeos, aqui você tem conteúdo e mais GB para a sua diversão.',
      qtd: 20,
      bonus: '20GB',
      imagem: '/img/max-1@2x.png',
      valor: '99,90',
      url: 'https://example.com/contratar/intermediario',
      minutos: 120,
      sms: 120,
      cobertura: '4G/5G',
      chipHello: 'GRÁTIS',
      frete: 'GRÁTIS',
      total: '99,90',
    },
    {
      nome: 'Controle Pro + MAX',
      idPlano: '1991',
      gb: 60,
      descricao: 'O máximo de dados móveis para quem vive sempre online; Séries, Jogos Mobile e muito mais sem se preocupar com consumo.',
      qtd: 30,
      bonus: '30GB',
      imagem: '/img/max-1@2x.png',
      valor: '119,90',
      url: 'https://example.com/contratar/intermediario',
      minutos: 200,
      sms: 150,
      cobertura: '4G/5G',
      chipHello: 'GRÁTIS',
      frete: 'GRÁTIS',
      total: '119,90',
    },
  ];
  res.status(200).json(plans);
};

export default handler;